# Use an official lightweight Python image.
FROM pybase_image:latest

WORKDIR /app/ai-python
# Copy the current directory contents into the container at /app
WORKDIR /app/ai-python

# Make port 80 available to the world outside this container
EXPOSE 9089

# Define environment variable for FastAPI to run in production
ENV NAME=World
