class REFORMED_QUERY:
      QUERY_LIMIT_CHECK=1000
      REFORMED_QUERY_LIMIT=1000
class QUOTES:
      UNWANTED_QUOTES =["'''", '"""', '"', "'", '`','’', '‘','“','‘']

class CanvasConfig:
    MAX_TOKEN_LIMIT = 10000
    TOP_K = 4
    CUSTOM_GPT="OPEN_AI_CUSTOM_GPT_WITH_DOC"
    OPEN_AI="OPEN_AI"
    OPEN_AI_WITH_DOC="OPEN_AI_WITH_DOC"
    OPEN_AI_CHAT_CANVAS="OPEN_AI_CHAT_CANVAS"
    PERPLEXITY="PERPLEXITY"
